In [22]:
from psychopy import visual, core
import numpy as np

t_cross = 2
t_cue = 3
t_rest_mean = 2

## Hyperparameters --------------------------------------------------------------------------------------------------------
# Cue Parameters --------------------------------------------------------------
arrow_size = 750             # Arrow Size
n_trials  = [15, 15, 15, 0]  # Number of each class (None, Right, Left, Down)
trial_length = 3             # Length of arrow display [sec]
blink_freq = 0               # Arrow blinking frequency [Hz]

# Classification Hyperparameters ----------------------------------------------
# -- |Train Data| --
participant_id = 0
session = 3
initial_run = 1
n_run = 5

# -- |Time Parameters| --
# Offline
tmin= -0.1
tmax= 3
t_baseline_offline = 0.1
# Online
classification_cycle_period = 0.2
classification_window_length = 0.5
t_baseline_online = 0.1

## Cue Preparation --------------------------------------------------------------------------------------------------------
# -- |Create random label sequence| --
labels = np.zeros(n_trials[0], dtype='int')
for i in range(1,len(n_trials)):
    labels = np.concatenate((labels,np.full(n_trials[i],i, dtype='int')))
np.random.shuffle(labels)

# -- |Define Display| --
win = visual.Window(color=(-255, -255, -255), fullscr=True, units = 'pix', screen = 1)

# -- |Shapes| --
def box(pos = (0,0), x = 0, y = 0, color = 'red', size = 1):
    x_neg = x if x < 0 else 0
    x_pos = x if x > 0 else 0

    y_neg = y if y < 0 else 0
    y_pos = y if y > 0 else 0

    return visual.ShapeStim(win, vertices=[(x_neg, -30 + y_neg),(x_pos, -30 + y_neg),(x_pos, 30 + y_pos),(x_neg, 30 + y_pos)], interpolate=True, fillColor=color, pos=pos, size=size)
cross = visual.TextStim(win, text='+', height=50)

# Arrow Vertices
arrow = [[(0,0)],                                                                   # 0 - None
         [(-0.2,0.05),(-0.2,-0.05),(0,-0.05),(0,-0.1),(.2,0),(0,0.1),(0,0.05)],     # 1 - Right
         [(.2,0.05),(.2,-0.05),(0,-0.05),(0,-0.1),(-0.2,0),(0,0.1),(0,0.05)],       # 2 - Left
         [(0.05,0.2),(-0.05,0.2),(-0.05,0),(-0.1,0),(0,-.2),(0.1,0),(0.05,0)]]      # 3 - Down
# Arrow Position
arrow_pos = np.array([(0,0),(0.3,0),(-0.3,0),(0,-0.3)]) # [None, Right, Left, Down]

# Arrow Shapes
arrows = []
for i in range(len(arrow)):
    arrows.append(visual.ShapeStim(win, vertices=arrow[i], interpolate=True, fillColor='red', pos=(0,0), size=arrow_size))

def state(s):
    state.value = s
def t_sm():
    t_sm.counter += classification_cycle_period

t_sm.counter = 0    # Initial State Machine Time
state(0)            # Initial State
cue_update_flag = False

def cue_state_machine(trial):
    if state.value == 0:
        cross.draw()
        t_sm()
        if t_sm.counter > t_cross:
            t_sm.counter = 0
            state(1)
    elif state.value == 1:
        arrows[labels[trial]].draw() 
        t_sm()
        if t_sm.counter > t_cue:
            t_sm.counter = 0
            state(2)
            t_rest = (t_rest_mean - 0.5) + np.random.rand()
    elif state.value == 2:
        t_sm()
        if t_sm.counter > t_rest:
            t_sm.counter = 0
            cue_update_flag = True
            state(0)

In [25]:
type(5//3)

int

In [2]:
import numpy as np

In [39]:
Pscores = np.array([2,8])
k = 3

np.where(np.array([k,k]) < Pscores,'#751818','gray')

array(['#751818', 'gray'], dtype='<U7')

In [4]:
a = np.array([0, 1, 2])
b = 1

c = a+b
c

array([1, 2, 3])

# Scores calculation simulation (Double model)

In [333]:
n_trials  = [15, 15, 15, 0]     # Number of each class (None, Right, Left, Down)
t_cue = 3
classification_cycle_period = 0.1

events_id = {'none': 0, 'right': 1, 'left': 2}

def confusion_matrix(TP,FN,FP,TN):
    # -- |Results calculation| --
    accuracy = (TP + TN)/(TP + FP + TN + FN)

    if TP + FP == 0:
        precision = np.NaN
    else:
        precision = TP/(TP + FP)
    
    if TP + FN == 0:
        recall = np.NaN
    else:
        recall = TP/(TP + FN)
        
    f1 = 2*(precision*recall)/(precision + recall)

    # -- |Results display| --
    print('Confusion Matrix')
    print('--------------------------------------')
    print('|            |       Predicted       |')
    print('|            -------------------------   Accuracy  = {0:}'.format(accuracy))
    print('|            |     P     |     N     |')
    print('--------------------------------------   Precision = {0:}'.format(precision))
    print("|        | P |   {0:^5d}   |   {1:^5d}   |   Recall    = {2:}".format(TP, FN, recall))
    print('| Actual -----------------------------')
    print("|        | N |   {0:^5d}   |   {1:^5d}   |   F1-score  = {2:}".format(FP, TN, f1))
    print('--------------------------------------')

    return [accuracy, precision, recall, f1]

# -- |Create random label sequence| --
labels = np.zeros(n_trials[0], dtype='int')
for i in range(1,len(n_trials)):
    labels = np.concatenate((labels,np.full(n_trials[i],i, dtype='int')))
np.random.shuffle(labels)

j = 0
p = []
Pscores = np.array([0,0])
Nscores = np.array([0,0])
Pscores_history = []
Nscores_history = []
while j < len(labels):
    label = labels[j]
    for i in range(2):
        Pscores[i] = np.random.randint(0,30)
        Nscores[i] = 30 - Pscores[i]
    Pscores_history.append([label, Pscores])
    Nscores_history.append([label, Nscores])
    Pscores = np.array([0,0])
    Nscores = np.array([0,0])
    j += 1

Pscores_history = np.array(Pscores_history, dtype='object')
Nscores_history = np.array(Nscores_history, dtype='object')

positive = []
negative = []
for l in range(np.max(list(events_id.values())) + 1):
    Pscores_total = np.array([sh[1] for sh in Pscores_history if sh[0] == l])
    Pscores_total = np.sum(Pscores_total, axis = 0)
    positive.append(Pscores_total)

    Nscores_total = np.array([sh[1] for sh in Nscores_history if sh[0] == l])
    Nscores_total = np.sum(Nscores_total, axis = 0)
    negative.append(Nscores_total)

positive = np.array(positive)
negative = np.array(negative)
print('Left Model Performance')
confusion_matrix(positive[events_id['left']][0],negative[events_id['left']][0],(np.sum(positive[:,0]) - positive[events_id['left']])[0],(np.sum(negative[:,0]) - negative[events_id['left']])[0])
print('Right Model Performance')
confusion_matrix(positive[events_id['right']][1],negative[events_id['right']][1],(np.sum(positive[:,0]) - positive[events_id['right']])[1],(np.sum(negative[:,0]) - negative[events_id['right']])[1])

Left Model Performance
Confusion Matrix
--------------------------------------
|            |       Predicted       |
|            -------------------------   Accuracy  = 0.4288888888888889
|            |     P     |     N     |
--------------------------------------   Precision = 0.24564183835182252
|        | P |    155    |    295    |   Recall    = 0.34444444444444444
| Actual -----------------------------
|        | N |    476    |    424    |   F1-score  = 0.28677150786308975
--------------------------------------
Right Model Performance
Confusion Matrix
--------------------------------------
|            |       Predicted       |
|            -------------------------   Accuracy  = 0.585925925925926
|            |     P     |     N     |
--------------------------------------   Precision = 0.41362916006339145
|        | P |    261    |    189    |   Recall    = 0.58
| Actual -----------------------------
|        | N |    370    |    530    |   F1-score  = 0.4828862164662349
---

[0.585925925925926, 0.41362916006339145, 0.58, 0.4828862164662349]

# Scores calculation simulation (Single model)

In [607]:
n_trials  = [0, 15, 15, 0]     # Number of each class (None, Right, Left, Down)
t_cue = 3
classification_cycle_period = 0.1

decision_threshold = 0

events_id = {'none': 0, 'right': 1, 'left': 2}

def confusion_matrix(TP,FN,FP,TN):
    # -- |Results calculation| --
    accuracy = (TP + TN)/(TP + FP + TN + FN)

    if TP + FP == 0:
        precision = np.NaN
    else:
        precision = TP/(TP + FP)
    
    if TP + FN == 0:
        recall = np.NaN
    else:
        recall = TP/(TP + FN)
        
    f1 = 2*(precision*recall)/(precision + recall)

    # -- |Results display| --
    print('Confusion Matrix')
    print('--------------------------------------')
    print('|            |       Predicted       |')
    print('|            -------------------------   Accuracy  = {0:}'.format(accuracy))
    print('|            |     P     |     N     |')
    print('--------------------------------------   Precision = {0:}'.format(precision))
    print("|        | P |   {0:^5d}   |   {1:^5d}   |   Recall    = {2:}".format(TP, FN, recall))
    print('| Actual -----------------------------')
    print("|        | N |   {0:^5d}   |   {1:^5d}   |   F1-score  = {2:}".format(FP, TN, f1))
    print('--------------------------------------')

    return [accuracy, precision, recall, f1]

# -- |Create random label sequence| --
labels = np.zeros(n_trials[0], dtype='int')
for i in range(1,len(n_trials)):
    labels = np.concatenate((labels,np.full(n_trials[i],i, dtype='int')))
np.random.shuffle(labels)

j = 0
p = []
Pscores = np.array([0,0])
Nscores = 0
Pscores_history = []
Nscores_history = []
while j < len(labels):
    label = labels[j]

    for i in range(30):
        prob = np.random.rand()
        p = [prob, 1-prob]

        if np.abs(p[0] - p[1]) > decision_threshold:
            Pscores[np.argmax(p)] += 1
        else:
            Nscores += 1

    Pscores_history.append([label, Pscores])
    Nscores_history.append([label, Nscores])

    Pscores = np.array([0,0])
    Nscores = 0

    j += 1

Pscores_history = np.array(Pscores_history, dtype='object')
Nscores_history = np.array(Nscores_history)

positive = []
negative = []
for l in range(np.max(list(events_id.values())) + 1):
    Pscores_total = np.array([sh[1] for sh in Pscores_history if sh[0] == l])
    Pscores_total = np.sum(Pscores_total, axis = 0)
    if Pscores_total.all() == 0:
        Pscores_total = np.array([0,0])
    positive.append(Pscores_total)

    Nscores_total = np.array([sh[1] for sh in Nscores_history if sh[0] == l])
    Nscores_total = np.sum(Nscores_total, axis = 0)
    negative.append(Nscores_total)

positive = np.array(positive, dtype = 'int')
negative = np.array([negative], dtype = 'int').T

matrix = np.concatenate((negative,positive),axis=1)
multiclass_confusion_matrix(matrix)

Confusion Matrix
--------------------------------------------------
|            |             Predicted             |
|            -------------------------------------
|            |     N     |     R     |     L     |
--------------------------------------------------
|        | N |     0     |     0     |     0     |
|        -----------------------------------------
| Actual | R |     0     |    220    |    230    |
         -----------------------------------------
|        | L |     0     |    218    |    232    |
--------------------------------------------------
Class N Performance:
   Accuracy  = 1.0
   Precision = nan
   Recall    = nan
   F1-score  = nan

Class R Performance:
   Accuracy  = 0.6676557863501483
   Precision = 0.502283105022831
   Recall    = 0.4888888888888889
   F1-score  = 0.49549549549549554

Class L Performance:
   Accuracy  = 0.6676557863501483
   Precision = 0.5021645021645021
   Recall    = 0.5155555555555555
   F1-score  = 0.5087719298245613



[[1.0, 0.6676557863501483, 0.6676557863501483],
 [nan, 0.502283105022831, 0.5021645021645021],
 [nan, 0.4888888888888889, 0.5155555555555555],
 [nan, 0.49549549549549554, 0.5087719298245613]]

In [582]:
def multiclass_confusion_matrix(matrix, class_name = ['N','R','L']):
    '''Display Confusion Matrix'''
    # -- |Results display| --
    print('Confusion Matrix')
    print('--------------------------------------------------')
    print('|            |             Predicted             |')
    print('|            -------------------------------------')
    print('|            |     {0}     |     {1}     |     {2}     |'.format(class_name[0],class_name[1],class_name[2]))
    print('--------------------------------------------------')
    print("|        | {0} |   {1:^5d}   |   {2:^5d}   |   {3:^5d}   |".format(class_name[0],matrix[0,0],matrix[0,1],matrix[0,2]))
    print('|        -----------------------------------------')
    print("| Actual | {0} |   {1:^5d}   |   {2:^5d}   |   {3:^5d}   |".format(class_name[1],matrix[1,0],matrix[1,1],matrix[1,2]))
    print('         -----------------------------------------')
    print("|        | {0} |   {1:^5d}   |   {2:^5d}   |   {3:^5d}   |".format(class_name[2],matrix[2,0],matrix[2,1],matrix[2,2]))
    print('--------------------------------------------------')

    accuracy = []
    precision = []
    recall = []
    f1_score  = []
    # -- |Results calculation| --
    for i in range(matrix.shape[0]):
        TP = matrix[i,i]
        FN = np.sum(matrix[i,:]) - matrix[i,i]
        FP = np.sum(matrix[:,i]) - matrix[i,i]
        TN = np.sum(matrix) - matrix[i,i]

        acc = (TP + TN)/(TP + FP + TN + FN)

        if TP + FP == 0:
            pre = np.NaN
        else:
            pre = TP/(TP + FP)
        
        if TP + FN == 0:
            rec = np.NaN
        else:
            rec = TP/(TP + FN)
            
        f1 = 2*(pre*rec)/(pre + rec)

        print(f'Class {class_name[i]} Performance:')
        print(f'   Accuracy  = {acc}')
        print(f'   Precision = {pre}')
        print(f'   Recall    = {rec}')
        print(f'   F1-score  = {f1}\n')

        accuracy.append(acc)
        precision.append(pre)
        recall.append(rec)
        f1_score.append(f1)


    return [accuracy, precision, recall, f1_score]

In [562]:
matrix = np.concatenate((negative,positive),axis=1)
matrix

array([[  0.,   0.,   0.],
       [  0., 220., 230.],
       [  0., 239., 211.]])

In [554]:
negative

array([[ 16],
       [234],
       [212]])

In [558]:
positive

array([[  8,   6],
       [111, 105],
       [118, 120]])

In [509]:
decision_threshold = 0.5
Pscores = np.array([0,0])

In [521]:
prob = np.random.rand()
p = [prob, 1-prob]

if np.abs(p[0] - p[1]) > decision_threshold:
    Pscores[np.argmax(p)] += 1
Pscores

array([4, 1])